// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Microservices.Demo.Report.API.Domain.Entities
{
    public partial class PolicyValidityPeriod
    {
        public PolicyValidityPeriod()
        {
            Offer = new HashSet<Offer>();
            PolicyCover = new HashSet<PolicyCover>();
            PolicyVersionCoverPeriodPolicyValidityPeriod = new HashSet<PolicyVersion>();
            PolicyVersionVersionValidityPeriodPolicyValidityPeriod = new HashSet<PolicyVersion>();
        }

        public int PolicyValidityPeriodId { get; set; }
        public DateTime PolicyFrom { get; set; }
        public DateTime PolicyTo { get; set; }

        public virtual ICollection<Offer> Offer { get; set; }
        public virtual ICollection<PolicyCover> PolicyCover { get; set; }
        public virtual ICollection<PolicyVersion> PolicyVersionCoverPeriodPolicyValidityPeriod { get; set; }
        public virtual ICollection<PolicyVersion> PolicyVersionVersionValidityPeriodPolicyValidityPeriod { get; set; }
    }
}