// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Microservices.Demo.Report.API.Domain.Entities
{
    public partial class PolicyHolder
    {
        public PolicyHolder()
        {
            Offer = new HashSet<Offer>();
            PolicyVersion = new HashSet<PolicyVersion>();
        }

        public int PolicyHolderId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Pesel { get; set; }
        public int AddressId { get; set; }

        public virtual Address Address { get; set; }
        public virtual ICollection<Offer> Offer { get; set; }
        public virtual ICollection<PolicyVersion> PolicyVersion { get; set; }
    }
}